const CONFIGS = {
  LND_TLS_CERT: undefined,
  LND_MACAROON: undefined,
  LND_SOCKET: undefined,
  OPEN_NODE_KEY: undefined,
  SESSION_SECRET: undefined,
}

exports.CONFIG_KEYS = {
  LND_TLS_CERT: 'LND_TLS_CERT',
  LND_MACAROON: 'LND_MACAROON',
  LND_SOCKET: 'LND_SOCKET',
  OPEN_NODE_KEY: 'OPEN_NODE_KEY',
  SESSION_SECRET: 'SESSION_SECRET',
}

exports.CONFIGS = CONFIGS
